[project]
name = "openmotics"
version = "0.0.0"
description = "Homeassistant Custom Component for Renson (Openmotics)"
license = { text = "AGPLv3" }
authors = [{ name = "Wouter Coppens", email = "wouter.coppens@gmail.com" }]
readme = "README.md"
repository = "https://github.com/rensongroup/home-assistant"
keywords = [
    "aiohttp",
    "asyncio",
    "openmotics",
    "openmotics-api",
    "hacs",
    "hass.io",
    "hass",
    "hassio",
    "home assistant",
    "home-assistant",
    "homeassistant",
    "integration",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: GNU Affero General Public License v3"
]

requires-python = ">=3.11,<3.13"
dependencies = [
    "homeassistant>=2024.4.0",
# pyhaopenmotics = "0.0.1"
]

[project.urls]
Homepage = "https://github.com/rensongroup/home-assistant"
Documentation = ""
Changelog = "https://github.com/rensongroup/home-assistant/releases"
Support = ""
Issues = "https://github.com/rensongroup/home-assistant/issues"
Repository = "https://github.com/rensongroup/home-assistant"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["custom_components/openmotics"]

[tool.ruff]
src = ["custom_components/openmotics"]

[tool.ruff.lint]
ignore = [
  "ANN101", # Self... explanatory
  "ANN401", # Opiniated warning on disallowing dynamically typed expressions
  "D203", # Conflicts with other rules
  "D213", # Conflicts with other rules
  "TID252", # Relative imports
  "RUF012", # Just broken

  # Formatter conflicts
  "COM812",
  "COM819",
  "D206",
  "E501",
  "ISC001",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "W191",
]
select = ["ALL"]

[tool.ruff.lint.flake8-import-conventions.extend-aliases]
"homeassistant.helpers.area_registry" = "ar"
"homeassistant.helpers.config_validation" = "cv"
"homeassistant.helpers.device_registry" = "dr"
"homeassistant.helpers.entity_registry" = "er"
"homeassistant.helpers.issue_registry" = "ir"
voluptuous = "vol"

[tool.ruff.lint.isort]
force-sort-within-sections = true
known-first-party = [
    "homeassistant",
]
combine-as-imports = true

[tool.pylint."MESSAGES CONTROL"]
# Reasons disabled:
# format - handled by ruff
# duplicate-code - unavoidable
# used-before-assignment - false positives with TYPE_CHECKING structures
disable = [
  "abstract-method",
  "duplicate-code",
  "format",
  "unexpected-keyword-arg",
  "used-before-assignment",
]

[tool.rye]
managed = true
dev-dependencies = [
  "pre-commit>=3.6.0",
  "pre-commit-hooks>=4.5.0",
  "pylint>=3.1.0",
  "ruff>=0.3.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"